name: Netlify Deploy (React + TS + Tailwind)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # First setup (no cache yet)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Create package-lock.json in CI (if your repo doesn't have one)
      - name: Ensure lockfile
        run: |
          if [ ! -f package-lock.json ]; then
            npm install --package-lock-only --no-audit --no-fund
          fi

      # Re-setup Node with npm cache now that the lockfile exists
      - name: Setup Node.js with npm cache
        if: hashFiles('**/package-lock.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint (ESLint)
        run: npm run lint

      - name: Build (Vite)
        run: npm run build

      # OPTIONAL: keep build as artifact (useful for debugging)
      - name: Upload build artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      # Deploy to Netlify using the CLI (Command Line Interface [a text-based tool])
      # PRs (Pull Requests [proposed code changes]) -> Preview; push to main -> Production
      - name: Deploy to Netlify
        uses: South-Paw/action-netlify-cli@v2
        with:
          args: >
            deploy --dir=dist
            ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && '--prod' || '' }}
            --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
