# .github/workflows/deploy-netlify.yml
name: Netlify Deploy (Vite + TS)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js (JavaScript runtime)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      - name: Deploy to Netlify (Preview for PRs, Prod on main)
        uses: South-Paw/action-netlify-cli@v2
        with:
          args: >
            deploy
            --dir=dist
            ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && '--prod' || '' }}
            --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
